---
title: "NYU Langone NGS-Tumor 50 Next Generation Sequencing Panel"
author: "Stephen Kelly"
date: "9/6/2016"
output: html_document
params:
  summary_table_file: summary_table.tsv
  act_gene_file: gene_file.txt
  canonical_transcript_file: canon_file.txt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo = FALSE, include = FALSE}
library("xtable")

# get the items for the report
summary_table_file <- params$summary_table_file
act_gene_file <- params$act_gene_file
canonical_transcript_file <- params$canonical_transcript_file

# load report tables
summary_df <- read.delim(summary_table_file, header = TRUE, sep = '\t')
canon_transcr_df <- read.delim(canonical_transcript_file, header = TRUE, sep = '\t')
act_genes <- scan(act_gene_file, what="", sep="\n")

# save current session
save.image(file="report_import.Rdata",compress = TRUE)


# filter the genes
gene_colname <- "Gene_ID"
act_genes[which(act_genes %in% summary_df[[gene_colname]])]

# get Known Significance actionable genes from summary table
known_gene_matches <- as.character(summary_df[which(act_genes %in% summary_df[[gene_colname]]),gene_colname])
# get the child docs for those genes
child_doc <- as.character(subset(canon_transcr_df, Gene  %in% known_gene_matches)[['Comment']])
# as.character(canon_transcr_df[which(known_gene_matches %in% canon_transcr_df[["Gene"]]),"Comment"])

# get the descriptions for the report genes
report_descr <- subset(canon_transcr_df, Gene  %in% known_gene_matches) #,"Description"])
```


# The following mutations are detected:

```{r, echo = FALSE, results='asis'}
# for(i in seq_along())
print(xtable(report_descr[c('Gene','Description')]),type='html', comment=FALSE, include.rownames=FALSE)
```


# Clinical Comments:

```{r, child = child_doc}
```

