---
title: "NYU Langone NGS-Tumor 50 Next Generation Sequencing Panel"
author: "Stephen Kelly"
date: "9/6/2016"
output:
  html_document:
    keep_md: yes
    # toc: yes
    # toc_float: yes
  rtf_document:
    keep_md: yes
---

```{r, echo = FALSE, include = FALSE}
library("xtable")
# get the items for the report

# summary_table_file <- "/ifs/home/kellys04/projects/clinical_genomic_reporting/reporter_output/R_2015_08_20_10_54_39_user_SN2-76-IT15-060-2/summary_table.tsv"
summary_table_file <- "./summary_table.tsv"

# load summary report table
summary_df <- read.delim(summary_table_file, header = TRUE, sep = '\t')
gene_colname <- "Gene_ID"

# load the list of actioanble genes
# act_gene_file <- "/ifs/home/kellys04/projects/clinical_genomic_reporting/reporter_data/actionable_genes.txt"
act_gene_file <- "./actionable_genes.txt"
act_genes <- scan(act_gene_file, what="", sep="\n")

act_genes[which(act_genes %in% summary_df[[gene_colname]])]


# canonical_transcript_file <- "/ifs/home/kellys04/projects/clinical_genomic_reporting/reporter_data/hg19/canonical_transcr_descr_comment_demo.tsv"
canonical_transcript_file <- "./canonical_transcr_descr_comment_demo.tsv"
canon_transcr_df <- read.delim(canonical_transcript_file, header = TRUE, sep = '\t')


# get Known Significance actionable genes from summary table
known_gene_matches <- as.character(summary_df[which(act_genes %in% summary_df[[gene_colname]]),gene_colname])
# get the child docs for those genes
child_doc <- as.character(subset(canon_transcr_df, Gene  %in% known_gene_matches)[['Comment']])
# as.character(canon_transcr_df[which(known_gene_matches %in% canon_transcr_df[["Gene"]]),"Comment"])

# get the descriptions for the report genes
report_descr <- subset(canon_transcr_df, Gene  %in% known_gene_matches) #,"Description"])
```


# The following mutations are detected:

```{r, echo = FALSE, results='asis'}
# for(i in seq_along())
print(xtable(report_descr[c('Gene','Description')]),type='html', comment=FALSE, include.rownames=FALSE)
```


# Clinical Comments:

```{r, child = child_doc}
```


